import glob
from setuptools import setup, find_packages

setup(
    name="fastink",
    version="1.0.0",
    author="Computing Center, IHEP",
    author_email="shijy@ihep.ac.cn",
    description="FastINK computing platform",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://code.ihep.ac.cn/INK/ink",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    scripts=glob.glob("bin/ink*"),
    classifiers=[
        "Programming Language :: Python :: 3",
    ],
    python_requires=">=3.9",
    install_requires=[
        "async_timeout",
        "concurrent-log-handler",
        "cryptography",
        "datetime",
        "elasticsearch==8.18.0",
        "fastapi",
        "fastapi_utils",
        "filelock",
        "htcondor",
        "httpx",
        "influxdb",
        "paramiko",
        "pexpect",
        "pymysql",
        "pytest",
        "python-dateutil",
        "python-multipart",
        "pytz",
        "pyyaml",
        "redis",
        "requests",
        "sh",
        "sqlalchemy",
        "typing-inspect",
        "ujson",
        "uvicorn",
        "websockets",
    ],
)
