# Require authentication and integrity checking by default.
use SECURITY : With_Authentication

# Host-based security is fine in a trusted local container environment.
use SECURITY : Host_Based

ALLOW_ADMINISTRATOR = root@$(UID_DOMAIN) condor@$(UID_DOMAIN) $(ALLOW_ADMINISTRATOR)

if version >= 8.9.7
    SEC_DEFAULT_AUTHENTICATION_METHODS = FS, IDTOKENS
else
    SEC_DEFAULT_AUTHENTICATION_METHODS = FS, TOKEN
endif

ALLOW_READ = *
SEC_READ_AUTHENTICATION = OPTIONAL
