COLLECTOR_NAME = collector
SCHEDD_NAME = schedd

BIND_ALL_INTERFACES = True

ALLOW_ADMINISTRATOR = root@$(UID_DOMAIN) condor@$(UID_DOMAIN)

POOL_HISTORY_DIR = /var/log/condor/PoolLog
KEEP_POOL_HISTORY = true

NEGOTIATOR_CONSIDER_PREEMPTION = False
PREEMPTION_REQUIREMENTS = False
NEGOTIATOR_CONSIDER_EARLY_PREEMPTION = False
NEGOTIATOR_DEPTH_FIRST = false

SEC_DEFAULT_AUTHENTICATION = OPTIONAL
SEC_DEFAULT_AUTHENTICATION_METHODS = CLAIMTOBE
SEC_DEFAULT_ENCRYPTION = OPTIONAL
SEC_DEFAULT_INTEGRITY = OPTIONAL

ALLOW_READ = *
ALLOW_WRITE = *
ALLOW_ADMINISTRATOR = *
ALLOW_NEGOTIATOR = *
ALLOW_DAEMON = *
ALLOW_CLIENT = *
ALLOW_NEGOTIATOR_SCHEDD = $(COLLECTOR_HOST), $(FLOCK_NEGOTIATOR_HOSTS)
ALLOW_WRITE_COLLECTOR = $(ALLOW_WRITE), $(FLOCK_FROM)
ALLOW_WRITE_STARTD = $(ALLOW_WRITE), $(FLOCK_FROM)
ALLOW_READ_COLLECTOR = $(ALLOW_READ), $(FLOCK_FROM)
ALLOW_READ_STARTD = $(ALLOW_READ), $(FLOCK_FROM)

SEC_DEFAULT_SESSION_DURATION = 1
SEC_DAEMON_AUTHENTICATION_METHODS = CLAIMTOBE,FS
SEC_DAEMON_INTEGRITY = OPTIONAL

PRIVATE_NETWORK_NAME = "fastink-htcondor"
COLLECTOR_HOST = $(CONDOR_HOST)
