# Register jobs with [job:<name>] sections.
# script is resolved relative to $FASTINK_CRON_BASE_DIR/jobs.

[job:job_queue_renew]
script=job_queue_renew.py
interval=5
mode=delay

[job:job_submit]
script=job_submit.py
interval=5
mode=delay

[job:reset_job_time]
script=reset_job_time.py
interval=1800
mode=fixed
